# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e89783ae53c37ab5323d668b1f9001eb77471a94b68f13c39457c7ff3d95de0f6e370203a67c9b60a4e10c6f01fb9bafad290cd75d7b1ef9df8811a81dfd4f9

test:
  secret_key_base: 8c8bb2c17e6568510218933982f7c1ee61ba59995f4c7e273c0fdfdb7d49b2b826316d75913ed4b92b1eba9777cdfbb7a4d5f452a5a56c4f8d504470109d53dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
